# Generated by Django 2.2.4 on 2019-09-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['ordem'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='arquivo',
            options={'ordering': ['ordem'], 'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['ordem'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['ordem'], 'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data_inscricao',
            new_name='data_avaliacao',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nome',
            new_name='titulo',
        ),
    ]
