# Generated by Django 2.2.4 on 2019-10-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arquivo',
            unique_together={('titulo', 'unidade')},
        ),
        migrations.AlterUniqueTogether(
            name='questionario',
            unique_together={('titulo', 'unidade')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('titulo', 'unidade')},
        ),
    ]
