# Generated by Django 2.2.4 on 2019-10-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191012_0934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alternativa',
            unique_together={('questao', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='arquivo',
            unique_together={('ordem', 'unidade')},
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together={('questionario', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='questionario',
            unique_together={('ordem', 'unidade')},
        ),
        migrations.AlterUniqueTogether(
            name='unidade',
            unique_together={('curso', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('unidade', 'ordem')},
        ),
    ]
