# Generated by Django 2.2.4 on 2019-09-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190905_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='obteve_certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='percentual_acertos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='percentual_andamento',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
