# Generated by Django 2.2.4 on 2019-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191012_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_publicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
