# Generated by Django 2.2.4 on 2019-10-26 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_curso_data_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessado', models.BooleanField(default=True)),
                ('data_acesso', models.DateTimeField(auto_now=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arquivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registros Usuários - Arquivos',
            },
        ),
    ]
