# Generated by Django 2.2.4 on 2019-10-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuarioarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioquestionario',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarioarquivo',
            name='acessado',
            field=models.BooleanField(default=False),
        ),
    ]
