# Generated by Django 2.2.4 on 2019-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190907_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovideo',
            name='asssitido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariovideo',
            name='data_assistido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariovideo',
            name='tempo_corrente',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuariovideo',
            name='acessado',
            field=models.BooleanField(default=True),
        ),
    ]
