# Generated by Django 2.2.4 on 2019-11-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191026_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_instrutor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
