# Generated by Django 2.2.4 on 2019-09-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190908_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariovideo',
            old_name='asssitido',
            new_name='assistido',
        ),
    ]
