# Generated by Django 2.2.4 on 2019-11-07 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_curso_nome_instrutor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioarquivo',
            unique_together={('arquivo', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioresposta',
            unique_together={('usuario', 'questao')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariovideo',
            unique_together={('video', 'usuario')},
        ),
    ]
