# Generated by Django 2.2.4 on 2019-11-07 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20191107_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioquestionario',
            unique_together={('usuario', 'questionario')},
        ),
    ]
