# Generated by Django 2.2.4 on 2019-09-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190909_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo',
            old_name='arquivo',
            new_name='caminho',
        ),
    ]
