# Generated by Django 2.2.4 on 2019-11-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191107_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioquestionario',
            name='percentual_acertos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuarioresposta',
            name='alternativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Alternativa'),
        ),
    ]
