# Generated by Django 2.2.4 on 2019-11-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191107_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='descricao',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_instrutor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='descricao',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
