# Generated by Django 2.2.4 on 2019-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inscricao_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovideo',
            name='assistido_denovo',
            field=models.BooleanField(default=False),
        ),
    ]
