# Generated by Django 2.2.4 on 2019-11-08 21:17

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191107_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='caminho',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='arquivos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='caminho',
            field=models.FileField(blank=True, default=None, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='videos'),
        ),
    ]
