# Generated by Django 2.2.4 on 2019-09-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuariovideo_assistido_denovo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariovideo',
            name='assistido_denovo',
        ),
    ]
