# Generated by Django 2.2.4 on 2019-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_usuariovideo_assistido_denovo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ultimo_conteudo_acessado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
