# Generated by Django 2.2.4 on 2019-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191108_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arquivo_media_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='arquivo_media_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
