# Generated by Django 2.2.4 on 2019-11-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191109_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
