# Generated by Django 2.2.4 on 2019-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190926_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aluno'), (2, 'Instrutor')], null=True),
        ),
    ]
